### PR TITLE
PR for review of version 1.0 CSS library 

### PR DESCRIPTION
**Pull request by MdBilal420**
Name: Mohammad Bilal
Live link: https://messyui.netlify.app/index.html

Do provide your feedback on what needs to be changed for a better version.
Thanks!

### CODE REVIEW

**Comment by akashmehrotra29** [comment]
-Code is very clean and readable. Files are very well structured.
-Work upon responsiveness to make it mobile friendly.
-Add some social media handlers, so that everyone can connect with you.

**Comment by MinakshiMittal** [comment]
Everything looks good. You can add more features like vertical nav, link buttons and many more. You can also add a link which will lead to your github repository.

**Comment by MdBilal420** [comment]
> -Code is very clean and readable. Files are very well structured.
> -Work upon responsiveness to make it mobile friendly.
> -Add some social media handlers, so that everyone can connect with you.

Thanks Akash.... surely will add the social media handlers.

**Comment by MdBilal420** [comment]
> Everything looks good. You can add more features like vertical nav, link buttons and many more. You can also add a link which will lead to your github repository.

Thanks Minakshi....will do the required changes in V2.0

**Comment by Xdev200** [comment]
Clean Design

1. Alert - add padding, align text to the center, adjust the width
2. badge - add top and bottom padding will make it great.
3. button - add more width will make your button looks good also you add border-radius
4. Card - add padding left and right
5. List  - add a hover effect
6. Modal - animation is only executing for the first time.
7. navigation - on a hover center the text and adjust the border width

**Comment by SurajGupta07** [comment]
Nice Work,
1) Footer is out of its position for a few of the components.
2) side list of the content table can occupy the entire page.

**Pull request closed without merging**
